# Last modified: 2025-09-03 10:39:02
appVersion = "0.0.1"
"""
Gradio app for image description using FastVLM-1.5B.

This script wraps the provided model loading and inference code into a simple
Gradio interface. Users can upload an image, and the app will return a detailed
description generated by the model. The model and tokenizer are loaded once at
startup to avoid redundant downloads on each inference call. The app relies
on Hugging Face Transformers and assumes the `apple/FastVLM-1.5B` model is
available. If you run this script without a GPU, it will automatically
fallback to CPU inference.

Usage:
    python gradio_app.py

Launches a local Gradio server at http://localhost:7860/ by default.
"""

import os
import torch
from PIL import Image
from transformers import AutoTokenizer, AutoModelForCausalLM
import gradio as gr

# Model identifier and special token configuration.  The IMAGE_TOKEN_INDEX is
# inserted into the text sequence to indicate where the vision features
# belong.  It must match the value expected by the underlying model code.
MID = "apple/FastVLM-1.5B"
MODEL_LOCAL_DIR = os.path.join("models", "FastVLM-1.5B")
IMAGE_TOKEN_INDEX = -200


def load_model():
    """Load the tokenizer and language model once.

    Returns a tuple of (tokenizer, model) on the appropriate device.
    """
    # Determine the appropriate dtype based on hardware availability.  Use
    # float16 on GPU for efficiency; fall back to float32 on CPU.
    dtype = torch.float16 if torch.cuda.is_available() else torch.float32
    # Prefer a local copy in models/FastVLM-1.5B if available. Otherwise
    # load from Hugging Face, caching into the local models directory.
    source_path = MODEL_LOCAL_DIR if os.path.isdir(MODEL_LOCAL_DIR) else MID
    tokenizer = AutoTokenizer.from_pretrained(
        source_path,
        trust_remote_code=True,
        cache_dir=MODEL_LOCAL_DIR if source_path == MID else None,
        local_files_only=source_path == MODEL_LOCAL_DIR,
    )
    model = AutoModelForCausalLM.from_pretrained(
        source_path,
        torch_dtype=dtype,
        device_map="auto",
        trust_remote_code=True,
        cache_dir=MODEL_LOCAL_DIR if source_path == MID else None,
        local_files_only=source_path == MODEL_LOCAL_DIR,
    )
    return tokenizer, model


# Load tokenizer and model at import time to avoid repeated downloads.
TOKENIZER, MODEL = load_model()


def describe_image(img: Image.Image) -> str:
    """Generate a detailed description for the uploaded image.

    Args:
        img: A PIL Image object.

    Returns:
        A string containing the model's description of the image.
    """
    # Build the chat template.  The model expects a prompt containing
    # `<image>` where the vision features will be inserted.  We use
    # 'Describe this image in detail.' as the instruction.
    messages = [{"role": "user", "content": "<image>\nDescribe this image in detail."}]
    rendered = TOKENIZER.apply_chat_template(
        messages, add_generation_prompt=True, tokenize=False
    )
    # Split the template around the <image> token.  We avoid adding special
    # tokens here so that we can insert the IMAGE_TOKEN_INDEX directly.
    pre, post = rendered.split("<image>", 1)
    pre_ids = TOKENIZER(
        pre, return_tensors="pt", add_special_tokens=False
    ).input_ids.to(MODEL.device)
    post_ids = TOKENIZER(
        post, return_tensors="pt", add_special_tokens=False
    ).input_ids.to(MODEL.device)
    # Create a tensor for the image token and concatenate with pre/post text.
    img_tok = torch.tensor(
        [[IMAGE_TOKEN_INDEX]], dtype=pre_ids.dtype, device=MODEL.device
    )
    input_ids = torch.cat([pre_ids, img_tok, post_ids], dim=1)
    # Build the attention mask (all ones) matching the input length.
    attention_mask = torch.ones_like(input_ids, device=MODEL.device)
    # Ensure the image is a PIL Image and preprocess it with the model's
    # vision tower.  The processor handles resizing, normalization, etc.
    if not isinstance(img, Image.Image):
        img = Image.fromarray(img)
    px = (
        MODEL.get_vision_tower()
        .image_processor(images=img, return_tensors="pt")["pixel_values"]
        .to(MODEL.device, dtype=MODEL.dtype)
    )
    # Generate the description.  We disable gradient calculation to save
    # memory and speed up inference.
    with torch.no_grad():
        output_ids = MODEL.generate(
            inputs=input_ids,
            attention_mask=attention_mask,
            images=px,
            max_new_tokens=128,
        )
    # Decode the output tokens to a human-readable string, skipping special
    # tokens.
    return TOKENIZER.decode(output_ids[0], skip_special_tokens=True)


def main():
    """Create and launch the Gradio interface."""
    interface = gr.Interface(
        fn=describe_image,
        inputs=gr.Image(type="pil"),
        outputs="text",
        title="Image Description using FastVLM-1.5B",
        description=(
            "Upload an image and receive a detailed description generated by the "
            "FastVLM-1.5B model. The model uses both vision and language "
            "capabilities to produce coherent, descriptive text."
        ),
    )
    # Launch the app. Setting share=False by default; set to True if you need
    # a public link via Gradio's servers.
    interface.launch()


if __name__ == "__main__":
    main()
